### ISSUE TITLE
浏览器插件

### ISSUE THREAD

**Issue by Tobeprmn** [Quorafind/Thino-Capture-Releases#1]
请问 Thino capture插件有上架edge浏览器扩展中心的打算吗？

**Comment by zhaoscsc** [comment]
希望可以支持Safari

**Comment by Quorafind** [comment]
已经安排了上架 chrome 商店，等待即可

**Comment by Quorafind** [comment]
刚刚查看了一下 已经上架，安装地址：https://chromewebstore.google.com/detail/thino-capture/oppagjehiimpjpjmgbfmanlnbpbcecff?hl=en&authuser=0
