### ISSUE TITLE
安装后报错

### ISSUE THREAD

**Issue by Tobeprmn** [Quorafind/Thino-Capture-Releases#2]
使用星愿浏览器安装后报错，如图。
![1](https://github.com/Quorafind/Thino-Capture-Releases/assets/119318291/8378ea8d-1dd7-46d3-a775-358573176421)
![2](https://github.com/Quorafind/Thino-Capture-Releases/assets/119318291/49837e6d-49da-41b2-9dd9-7fa59a0dc766)

**Comment by Quorafind** [comment]
部分低版本浏览器不支持侧边栏功能，你看下用 chrome 是否就能解决这个问题
